# Generated by Django 3.1.1 on 2020-09-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200909_1644'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomtype',
            new_name='room_type',
        ),
    ]
